<a href="https://colab.research.google.com/github/xpdlaldam/PyTorch/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hi2")

hi2


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
print(torch.__version__)

2.1.0+cu121


# Intro to Tensors

## Creating tensors

In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# Matrix
MATRIX = torch.tensor([[1, 2],
                       [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [2, 3, 4],
                        [2, 3, 7],
                        ]])

## Random tensors

In [13]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8397, 0.9963, 0.3892, 0.3250],
        [0.8820, 0.2419, 0.8849, 0.3558],
        [0.6521, 0.0972, 0.0601, 0.9500]])

In [14]:
random_tensor.dtype

torch.float32

In [15]:
one_to_ten = torch.arange(start = 1, end = 11, step=1)

In [16]:
# Create tensors like: make a same shape tensor with 0's from a different tensor
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [17]:
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None,
    device=None, # what device is your tensor on "cpu", "cuda"
    requires_grad=False # whether or not to track gradients with these tensor operations
)

In [18]:
# .type() convert/change float dtype from float32 to float16 using
float_16_tensor = float_32_tensor.type(torch.float16)

## Getting Tensor Attributes



In [19]:
## Three most important/common issue info from a tensor
some_tensor = torch.rand(3, 4)
some_tensor
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

torch.float32
torch.Size([3, 4])
cpu


## Matrix Multiplication using matmul and mm

In [20]:
%%time
tensor1 = torch.tensor([1, 2, 3])
torch.matmul(tensor1, tensor1)

CPU times: user 363 µs, sys: 0 ns, total: 363 µs
Wall time: 5.21 ms


tensor(14)

In [21]:
tensor1 = torch.tensor([
    [1, 2],
    [2, 3],
    [3, 4],
])
tensor1.shape

tensor2 = torch.tensor([
    [2, 3],
    [3, 4],
])

# mm only works for >= 2 shape matrices
torch.mm(tensor1, tensor2)

tensor([[ 8, 11],
        [13, 18],
        [18, 25]])

## Transpose a matrix

In [22]:
tensor1.T

tensor([[1, 2, 3],
        [2, 3, 4]])

## Tensor aggregation

In [23]:
x = torch.arange(0, 100, 10) + 1
x


tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [24]:
x.min(), x.max()

(tensor(1), tensor(91))

In [31]:
x.mean()

RuntimeError: ignored

In [36]:
x.dtype # int64 is Long dtype

torch.int64

In [37]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [38]:
x.sum()

tensor(460)

## Find positional min and max

In [39]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

## Reshaping, stacking, squeezing, unsqueezing tensors

* torch.reshape(input, shape):	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape()

* Tensor.view(shape): Returns a view of the original tensor in a different shape but shares the same data as the original tensor

* torch.stack(tensors, dim=0): Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size

* torch.squeeze(input):	Squeezes input to remove all the `1-Ds`

* torch.unsqueeze(input, dim):	Returns input with a dimension value of 1 added at dim

* torch.permute(input, dims):	Returns a view of the original input with its dimensions permuted (rearranged) to dims

In [41]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [42]:
## Add an extra D using reshape
# must match with original number of tensors
x_reshaped = x.reshape(1, 9) # 1 * 9 = 9
x_reshaped2 = x.reshape(3, 3) # 3 * 3 = 9
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [44]:
## Change the view
# a view of a tensor share the same memory as the original tensor
# hence if we change an element from a view so will the x
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [45]:
z[0, 0] = 99
z

tensor([[99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [46]:
x

tensor([99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [47]:
## Stack tensors on top of each other
torch.stack([x, x], dim=0) # vertical

tensor([[99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [48]:
torch.stack([x, x], dim=1) # horizontal

tensor([[99., 99.],
        [ 2.,  2.],
        [ 3.,  3.],
        [ 4.,  4.],
        [ 5.,  5.],
        [ 6.,  6.],
        [ 7.,  7.],
        [ 8.,  8.],
        [ 9.,  9.]])