<a href="https://colab.research.google.com/github/xpdlaldam/PyTorch/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hi2")

hi2


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
print(torch.__version__)

2.1.0+cu121


# Intro to Tensors

## Creating tensors

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[1, 2],
                       [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [2, 3, 4],
                        [2, 3, 7],
                        ]])

## Random tensors

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7441, 0.0244, 0.4048, 0.6732],
        [0.5977, 0.0854, 0.5637, 0.1906],
        [0.7489, 0.8159, 0.8341, 0.9082]])

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
one_to_ten = torch.arange(start = 1, end = 11, step=1)

In [ ]:
# Create tensors like: make a same shape tensor with 0's from a different tensor
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [ ]:
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None,
    device=None, # what device is your tensor on "cpu", "cuda"
    requires_grad=False # whether or not to track gradients with these tensor operations
)

In [ ]:
# .type() convert/change float dtype from float32 to float16 using
float_16_tensor = float_32_tensor.type(torch.float16)

## Getting Tensor Attributes



In [ ]:
## Three most important/common issue info from a tensor
some_tensor = torch.rand(3, 4)
some_tensor
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

torch.float32
torch.Size([3, 4])
cpu


## Matrix Multiplication using matmul and mm

In [ ]:
%%time
tensor1 = torch.tensor([1, 2, 3])
torch.matmul(tensor1, tensor1)

CPU times: user 401 µs, sys: 136 µs, total: 537 µs
Wall time: 6.82 ms


tensor(14)

In [ ]:
tensor1 = torch.tensor([
    [1, 2],
    [2, 3],
    [3, 4],
])
tensor1.shape

tensor2 = torch.tensor([
    [2, 3],
    [3, 4],
])

# mm only works for >= 2 shape matrices
torch.mm(tensor1, tensor2)

tensor([[ 8, 11],
        [13, 18],
        [18, 25]])

## Transpose a matrix

In [ ]:
tensor1.T

tensor([[1, 2, 3],
        [2, 3, 4]])

## Tensor aggregation

In [ ]:
x = torch.arange(0, 100, 10) + 1
x


tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
x.min(), x.max()

(tensor(1), tensor(91))

In [ ]:
x.mean()

RuntimeError: ignored

In [ ]:
x.dtype # int64 is Long dtype

torch.float32

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(15.8889), tensor(15.8889))

In [ ]:
x.sum()

tensor(143.)

## Find positional min and max

In [ ]:
x.argmin(), x.argmax()

(tensor(1), tensor(0))

## Reshaping, stacking, squeezing, unsqueezing tensors

* torch.reshape(input, shape):	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape()

* Tensor.view(shape): Returns a view of the original tensor in a different shape but shares the same data as the original tensor

* torch.stack(tensors, dim=0): Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size

* torch.squeeze(input):	Squeezes input to remove all the `1-Ds`

* torch.unsqueeze(input, dim):	Returns input with `a dimension value of 1 added at dim`

* torch.permute(input, dims):	Returns a view of the original input with its dimensions permuted (rearranged) to dims

In [1]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

### reshape

In [ ]:
## Add an extra D
# must match with original number of tensors
x_reshaped = x.reshape(1, 9) # 1 * 9 = 9
x_reshaped2 = x.reshape(3, 3) # 3 * 3 = 9
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

### view

In [ ]:
### view
## Change the view
# a view of a tensor shares the same memory as the original tensor
# hence if we change an element from a view, so will the x
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[0, 0] = 99
z

tensor([[99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [ ]:
x

tensor([99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

### stack

In [ ]:
### stack
## Stack tensors on top of each other
torch.stack([x, x], dim=0) # vertical

tensor([[99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [ ]:
torch.stack([x, x], dim=1) # horizontal

tensor([[99., 99.],
        [ 2.,  2.],
        [ 3.,  3.],
        [ 4.,  4.],
        [ 5.,  5.],
        [ 6.,  6.],
        [ 7.,  7.],
        [ 8.,  8.],
        [ 9.,  9.]])

### squeeze

In [ ]:
### squeeze
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped

tensor([[99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [ ]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [ ]:
x_squeezed.shape # shape reduced from [1, 9] to [9]

torch.Size([9])

### unsqueeze

In [ ]:
x_squeezed.shape

torch.Size([9])

In [ ]:
# x_reshaped.shape is [1, 9]. The first dimension (dim=0) is 1 and the second dimension (dim=1) is 9
# hence if we apply this logic to x_squeezed which has shape [9]:
# unsqueeze(dim=0) is adding 1-D to the 1st dimension
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed.shape

torch.Size([1, 9])

In [ ]:
# unsqueeze(dim=1) is adding 1-D to the 2nd dimension
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed.shape

torch.Size([9, 1])

### permute

#### permute is a view, hence it shares the same memory with the original unpermuted tensor

In [ ]:
x = torch.randn(2, 3, 4) # think of it as: there are two (3 by 4) matrices
x

tensor([[[-0.4982,  0.5359, -2.3079,  0.8697],
         [ 0.6982, -0.1267, -2.0988,  0.3419],
         [-2.7829, -1.9161,  0.6646, -0.6073]],

        [[-1.1977, -0.9480,  1.8712,  0.7288],
         [-0.5791, -1.5871, -0.2040, -0.3361],
         [ 0.7211,  0.1002, -0.7070, -1.1027]]])

In [ ]:
x.shape

torch.Size([2, 3, 4])

In [ ]:
x_permuted = x.permute(2, 0, 1) # dim=2 is first, dim=0 is second, and dim=1 is last

In [ ]:
x_permuted

tensor([[[-0.4982,  0.6982, -2.7829],
         [-1.1977, -0.5791,  0.7211]],

        [[ 0.5359, -0.1267, -1.9161],
         [-0.9480, -1.5871,  0.1002]],

        [[-2.3079, -2.0988,  0.6646],
         [ 1.8712, -0.2040, -0.7070]],

        [[ 0.8697,  0.3419, -0.6073],
         [ 0.7288, -0.3361, -1.1027]]])

In [ ]:
x_permuted.shape # 4 (2 by 3) matrices

torch.Size([4, 2, 3])

## **Indexing**

In [ ]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# grabs the entire dim=0
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# grabs the first row from dim=1 (3 by 3 matrix)
x[0][0], x[0, 0] # these two are identical

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
# get all values from 0th dim but only grab the 0th row from dim=1
x[:, 0]

(tensor([[1, 2, 3]]), tensor([[1, 4, 7]]))

In [ ]:
# get all values from 0th dim but only grab the second row from dim=1
x[:, 2]

tensor([[7, 8, 9]])

In [ ]:
# get all values from 0th and 1st dims
x[:, :]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# get all values from dim=0 and dim=1 but only grab the first column of dim=2
x[:, :, 0]

tensor([[1, 4, 7]])

In [ ]:
# from dim=0, get all values from dim=1
x[0, :]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# from dim=0, get all values from dim=1, but only grab the first column from dim=2
x[0, :, 0]

tensor([1, 4, 7])

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# Index on x to return 9
x[0, 2, 2]

tensor(9)

In [ ]:
# Index on x to return 3, 6, 9
x[0, :, 2]

tensor([3, 6, 9])

## **pytorch tensors & numpy**

### numpy -> tensor

In [3]:
## default dtype
# numpy: float64
# torch: float32

## from_numpy(): np array -> tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [4]:
# tensor -> np array
tensor = torch.ones(7)
np_tensor = tensor.numpy()
tensor, np_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## **Reproducibility**

In [7]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

torch.rand(3,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

## **Running tensors and pytorch objects on GPUs (and making faster computations)**

In [1]:
!nvidia-smi

Wed Dec 27 06:14:18 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   67C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### Check for GPU access with pytorch

In [2]:
import torch
torch.cuda.is_available()

True

### Setup device agnostic code

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

### Count number of devices

In [4]:
torch.cuda.device_count()

1

### Putting tensors (and models) on the GPU

In [6]:
tensor = torch.tensor([1, 2, 3], device="cpu") # default device is "cpu"
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [7]:
# Move tensor to GPU (if available)
# the 0 from 'cuda:0' means the index of our gpu
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU

In [9]:
# As you can see numpy doesn't work with GPUs it only works with CPUs
tensor_on_gpu.numpy()

TypeError: ignored

In [10]:
tensor_back_on_cpi = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpi

array([1, 2, 3])