<a href="https://colab.research.google.com/github/xpdlaldam/PyTorch/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hi2")

hi2


In [ ]:
!nvidia-smi

Tue Dec 12 04:01:13 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   60C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [1]:
import torch
print(torch.__version__)

2.1.0+cu118


# Intro to Tensors

## Creating tensors

In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# Get tensor back as python int
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [4]:
# Matrix
MATRIX = torch.tensor([[1, 2],
                       [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3]
                        [2, 3, 4],
                        [2, 3, 7],
                        ]])

## 21. Random tensors

In [3]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6001, 0.8038, 0.6245, 0.2321],
        [0.7072, 0.3906, 0.5161, 0.1039],
        [0.1906, 0.4021, 0.5591, 0.7814]])

In [4]:
random_tensor.dtype

torch.float32

In [8]:
one_to_ten = torch.arange(start = 1, end = 11, step=1)

In [9]:
# Create tensors like: make a same shape tensor with 0's from a different tensor
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [ ]:
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None,
    device=None, # what device is your tensor on "cpu", "cuda"
    requires_grad=False # whether or not to track gradients with these tensor operations
)

In [ ]:
# change float dtype from float32 to float16
float_16_tensor = float_32_tensor.type(torch.float16)