<a href="https://colab.research.google.com/github/xpdlaldam/PyTorch/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hi2")

hi2


In [ ]:
!nvidia-smi

Tue Dec 12 04:01:13 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   60C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import torch
print(torch.__version__)

2.1.0+cu121


# Intro to Tensors

## Creating tensors

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[1, 2],
                       [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3]
                        [2, 3, 4],
                        [2, 3, 7],
                        ]])

## Random tensors

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6001, 0.8038, 0.6245, 0.2321],
        [0.7072, 0.3906, 0.5161, 0.1039],
        [0.1906, 0.4021, 0.5591, 0.7814]])

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
one_to_ten = torch.arange(start = 1, end = 11, step=1)

In [ ]:
# Create tensors like: make a same shape tensor with 0's from a different tensor
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [ ]:
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None,
    device=None, # what device is your tensor on "cpu", "cuda"
    requires_grad=False # whether or not to track gradients with these tensor operations
)

In [ ]:
# .type() convert/change float dtype from float32 to float16 using
float_16_tensor = float_32_tensor.type(torch.float16)

## Getting Tensor Attributes



In [ ]:
## Three most important/common issue info from a tensor
some_tensor = torch.rand(3, 4)
some_tensor
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

torch.float32
torch.Size([3, 4])
cpu


## Matrix Multiplication using matmul and mm

In [ ]:
%%time
tensor1 = torch.tensor([1, 2, 3])
torch.matmul(tensor1, tensor1)

In [13]:
tensor1 = torch.tensor([
    [1, 2],
    [2, 3],
    [3, 4],
])
tensor1.shape

tensor2 = torch.tensor([
    [2, 3],
    [3, 4],
])

# mm only works for >= 2 shape matrices
torch.mm(tensor1, tensor2)

tensor([[ 8, 11],
        [13, 18],
        [18, 25]])

## Transpose a matrix

In [14]:
tensor1.T

tensor([[1, 2, 3],
        [2, 3, 4]])

## Tensor aggregation

In [4]:
x = torch.arange(0, 100, 10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [8]:
x.min(), x.max()

(tensor(0), tensor(90))

In [14]:
x.mean()

RuntimeError: ignored

In [13]:
x.dtype # int64 is Long dtype

torch.int64

In [17]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [18]:
x.sum()

tensor(450)